Resource modules api and Testing
Apstra/aos-ansible pull request #15
Opened 2019-05-08 19:22 UTC by that1guy15

New resource modules:

- aos_vni_pool
- aos_ip_pool

Testing now includes ansible playbook for integration test. 
aos.py moved to library for cleaner install and use.

2019-05-09 21:21 UTC, roman-verchikov requested changes
Way too much copy/pasting. All the coding mistakes are spreading across codebase very quickly with this approach.

All the license headers should be revisited and made single line statements according to Ansible module development guide.

2019-05-09 21:21 UTC, roman-verchikov commented on README.md
> +## Current Modules
Not sure about the value of this section given that it simply enumerates existing files and doesn't provide any documentation on how to use it.

2019-05-09 21:21 UTC, roman-verchikov commented on README.md
> +`cd ./library
this will render into single line code statement. Use multi-line code syntax instead (```)

2019-05-09 21:21 UTC, roman-verchikov commented on README.md
> +`cd aos-ansible
same as above

2019-05-09 21:21 UTC, roman-verchikov commented on README.md
> +git clone https://github.com/Apstra/aos-ansible.git`
it might be better to use git submodules in this case, which would allow to reference `aos-ansible` repo instead of keeping a copy.

2019-05-09 21:21 UTC, roman-verchikov commented on README.md
> +[Adding new modules or roles](https://github.com/Apstra/aos-ansible/blob/develop/CONTRIBUTING.md)
I guess it would be better to simply state

> See CONTRIBUTING.md

The thing about HTTP links is that they tend to break. In this particular example the most likely case would be if we ditched `develop` branch and only used `master`. Other examples include moving source code to a different repository, renaming file, etc.

2019-05-09 21:21 UTC, roman-verchikov commented on README.md
> +Apache 2.0
License need to be revisited

2019-05-09 21:21 UTC, roman-verchikov commented on inventory.ini
> +aos3.0-l2-evpn	ansible_host=aos-testaosansiblel2ev-rh9yt9ie.srv.ravcloud.com
I guess it would be ok as first implementation, but later it should be replaced with travis encrypted environment variables: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +# This file is part of Ansible
I don't think this statement is accurate, given that this module is not going to be core ansible module.

Also it contradicts Ansible requirements for license headers: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#copyright-and-license.

> The license declaration should be ONLY one line, not the full GPL prefix.:

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +    for i, subnet in enumerate(subnets, 1):
`i` is unused

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +        except ValueError as e:
there can also be a `TypeError` in case user specifies `null` as subnet value

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +    else:
`elif my_pool['subnets']:`

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +        Only one of I(name), I(id) or I(content) can be set.
I don't see `content` defined anywhere

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +        Only one of I(name), I(id) or I(content) can be set.
`content` is referenced in documentation, but is not used anywhere

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +        if 'name' not in margs.keys():
`'name'` is also required for update

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +            module.exit_json(changed=True,
this is repeated below

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +        ip_pool_absent(module, margs['session'], endpoint, my_pool)
the contract between caller and callee and variable naming is too obscure. What is `my_pool`? Why is it `my`? Who's "me"?

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +        ip_pool_absent(module, margs['session'], endpoint, my_pool)
I'd suggest to rewrite using clear contract, something along these lines:

```python
target_state = margs["state"]

pool = find_resource_item(...)

if target_state == "absent":
    aos_pool_delete_by_id(session, pool["id"])
elif target_state == "present":
    pool_already_exists = pool != {}
    if pool_already_exists:
        aos_pool_update(session, pool["id"], pool)
    else:
        aos_pool_create(session, new_pool)
```

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +def validate_ranges(module, ranges):
identical function already present in `aos_asn_pool`. Isolate and reuse

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +        i += 1
one of the reasons you should isolate functions and reuse them: i+=1 is not needed here, yet copy/pasted from old implementation, which spreads bad code further

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +def vni_pool_present(module, session, my_pool):
the structure is identical to `ip_pool_present` and other `*_present` functions in other modules with all the mistakes copy/pasted. Isolate and reuse.

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_clean_up_tests/tasks/main.yml
> +    register: vnipool
newline

2019-05-09 21:21 UTC, roman-verchikov commented on test_playbook.yaml
> +---
Might also be good to run this test in `checked` mode to do pure unit testing.

2019-05-09 21:21 UTC, roman-verchikov commented on test_playbook.yaml
> +            msg: "Failure detected in test roles, cleaning up and reset environment"
add newline

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_asn_pool/tasks/main.yml
> +      name: "{{ asnpool.name }}"
test case when both name and id are provided

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_asn_pool/tasks/main.yml
> +        - asnpool.value == {}
newline

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_blueprint_deploy/tasks/main.yml
> +        - bp_deploy|changed == false
newline

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_ip_pool/tasks/main.yml
> +  - set_fact:
why not simply use list of pools?

```yaml
- set_fact:
    ip_pools:
        - network: '192.168.59.0/24'
        - network: '192.168.60.0/24'
        - network: '10.10.10.0/23'
        - network: '192.168.70.0/24'
        - network: '10.10.20.0/23'
```

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_ip_pool/tasks/main.yml
> +      ipv6_pool1:
same as above

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_ip_pool/tasks/main.yml
> +        - '192.168.359.0/24'
also test for `null` and empty input

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_ip_pool/tasks/main.yml
> +        - ip6pool.value == {}
newline

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_login/tasks/main.yml
> +        - "'Invalid credentials' in test.msg"
newline

2019-05-09 21:21 UTC, roman-verchikov commented on tests/roles/test_pb_aos_vni_pool/tasks/main.yml
> +        - vnipool.value == {}
newline

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +def vni_pool(module):
all the `*_pool` functions share the same pattern:

1. validate input
2. check if resource exists
3. if target state is "absent" - delete resource
4. if target state is "present" and resource does not exist yet - create it
5. if target state is "present" and resource already exists - update existing resource

All of this can be isolated and reused with minor changes to avoid copy/pasting

2019-05-09 21:21 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +    item_name = False
`item_name` and `item_id` must either be string or `None`

2019-05-10 17:14 UTC, roman-verchikov commented on tox.ini
> +    bash -ec 'if [[ $VAULT_PASSWORD ]]; then echo $VAULT_PASSWORD >> vault_pass.txt; fi'
I guess you need to overwrite instead of appending

```
echo $VAULT_PASSWORD > vault_pass.txt
```

2019-05-10 17:16 UTC, roman-verchikov commented on tox.ini
> +    bash -ec 'if [[ $VAULT_PASSWORD ]]; then echo $VAULT_PASSWORD >> vault_pass.txt; fi'
also password may contain whitespaces, so it would be better to use quotes:

```
if [[ ${VAULT_PASSWORD} ]]; then echo "${VAULT_PASSWORD}" >> vault_pass.txt; fi
```

2019-05-10 17:18 UTC, roman-verchikov requested changes

2019-05-10 17:18 UTC, roman-verchikov commented on tox.ini
> +    touch vault_pass.txt
I think touch is not necessary, if `${VAULT_PASSWORD}` is set, then redirecting (`echo ${VAULT_PASSWORD}`) will create new file if it doesn't exist, and if `VAULT_PASSWORD` is not set, then you don't even need a vault_pass.txt.

2019-05-10 17:19 UTC, roman-verchikov commented on inventory.ini
> +$ANSIBLE_VAULT;1.1;AES256
thats cool!

2019-05-10 17:20 UTC, roman-verchikov commented on tox.ini
> +    /usr/bin/touch
remove `touch`

2019-05-10 18:19 UTC, roman-verchikov commented on TESTING.md
> +tox
tox should take care of dependencies. The only requirement to run it - is to have tox installed, so the only thing a user need to do to run tests is to run tox:

```
tox
```

2019-05-10 18:20 UTC, roman-verchikov commented on TESTING.md
> +from `ansible.cfg` to be running or these tests will fail
you mean in inventory.ini?

2019-05-30 16:59 UTC, roman-verchikov requested changes

2019-05-30 16:59 UTC, roman-verchikov commented on library/aos_ip_pool.py
> +    for i, subnet in enumerate(subnets, 1):
not addressed: remove `i` and `enumerate`

2019-05-30 16:59 UTC, roman-verchikov commented on library/aos_vni_pool.py
> +    for i, vni_range in enumerate(ranges, 1):
remove `i` and `enumerate`, they are unused

2019-05-30 16:59 UTC, roman-verchikov commented on tests/roles/test_clean_up_tests/tasks/main.yml
> +          - "my-blank-ipv6-pool"
missing newline (and this nasty red symbol!)

2019-05-30 16:59 UTC, roman-verchikov commented on test_playbook.yaml
> +            msg: "Cleaning up after the mess. Nothing to see here, move along."
missing newline

2019-05-30 16:59 UTC, roman-verchikov commented on tests/roles/test_pb_aos_blueprint_deploy/tasks/main.yml
> +        # - bp_deploy|changed == false
remove commented line

2019-05-30 16:59 UTC, roman-verchikov commented on requirements.txt
> +tox==3.7.0
`tox` is not a dependency for any of the ansible modules, and should be removed from `requirements.txt`

2019-05-30 16:59 UTC, roman-verchikov commented on test-requirements.txt
> +tox==3.7.0
Even in this case, `tox` is not a dependency of tests (`tox` module is not imported by any test), instead it's an external tool used to run the tests. I guess the only place where `tox` should be mentioned is README and perhaps CI test script, where tox must be installed.

2019-05-30 16:59 UTC, roman-verchikov commented on test-requirements.txt
>  nose==1.3.7
nose dependency should be removed if you decided to switch to pytest, keeping multiple test libraries is confusing

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_login.py
`AnsibleExitJson` and `AnsibleFailJson` classes are unused

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_login.py
>      resp = aos_login.aos_login()
aos_login() expects one argument which is not provided. Not sure how this works

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_vni_pool.py
> +    resp = aos_vni_pool.vni_pool()
vni_pool() requires module passed as argument. I guess `aos_vni_pool` is mocked, and it doesn't really test anything?.. Not sure how it works

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_vni_pool.py
> +def test_aos_vni_pool_success(mock_module, mock_aos_vni_pool):
mock_module is unused

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_ip_pool.py
> +from ansible.compat.tests.mock import patch
missing copyright header

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_ip_pool.py
> +    resp = aos_ip_pool.ip_pool()
`ip_pool()` requires `module` argument passed, test seem to be testing mocked instance of ip_pool (in other words, does not test anything)

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_ip_pool.py
> +    mock_module.assert_called_with(
Not sure what this test does. It seems you already have higher-level tests that cover arguments being passed to playbook, so this can be removed

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_ip_pool.py
> +        self.addr_type = 'ipv4'
there's no need for `addr_type` to be an instance variable, it could be defined as a global or class variable, and thus would not require the object to maintain state

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_ip_pool.py
> +        self.addr_type = 'ipv6'
same as above

2019-05-30 16:59 UTC, roman-verchikov commented on tests/test_aos_vni_pool.py
> +    aos_vni_pool.main()
same as aos_ip_pool.

2019-05-30 16:59 UTC, roman-verchikov commented on tox.ini
> +    pytest -q tests/
IMHO it would be better to increase verbosity instead of decreasing it. `pytest -vv` would print the difference between expected and actual values for each failing test, which is very useful for debugging.

2019-05-30 18:52 UTC, that1guy15 commented on tests/test_aos_ip_pool.py
> +    mock_module.assert_called_with(
We have already covered this.
These test insure the args past into Ansible meet the requirements configured and what we expect.

2019-05-30 22:56 UTC, roman-verchikov commented on tests/test_aos_vni_pool.py
> +    resp = aos_vni_pool.vni_pool()
unresolved

2019-05-30 22:56 UTC, roman-verchikov commented on tests/test_aos_vni_pool.py
> +def test_aos_vni_pool_success(mock_module, mock_aos_vni_pool):
unresolved

2019-05-30 22:57 UTC, roman-verchikov commented on tests/test_aos_login.py
unresolved

2019-05-31 22:26 UTC, roman-verchikov commented on tests/test_aos_ip_pool.py
> +def test_aos_ip_pool_success(mock_module, mock_aos_ip_pool):
I guess it would be better to remove this test, because it's quite confusing and it's not clear what exactly is being tested.

2019-05-31 22:27 UTC, roman-verchikov commented on tests/test_aos_vni_pool.py
> +def test_aos_vni_pool_success(mock_module, mock_aos_vni_pool):
same here, would be better to remove this test

2019-05-31 22:31 UTC, roman-verchikov commented on tox.ini
> +    pytest -q tests/ -vv
remove the `-q` argument from pytest cli call, `-q` and `-vv` are mutually exclusive (-q == "quiet" vs -vv == "very verbose")

2019-06-03 18:28 UTC, roman-verchikov commented on requirements.txt
> +tox==3.7.0
unresolved

2019-06-03 18:30 UTC, roman-verchikov approved these changes
Looks ok with the tox dependency in requirements.txt addressed

2019-06-03 19:49 UTC, merged